In [1]:
pip install gym

Note: you may need to restart the kernel to use updated packages.


In [4]:
import gym
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import IPython

def show(states):
    fig = plt.Figure()
    ax = fig.subplots()
    ax.matshow(np.zeros([4,4]), cmap='bwr',alpha=0.0)
    sc = ax.scatter(0, 0, color='red', s=500)  
    ax.text(0, 0, 'start', ha='center', va='center')
    ax.text(3, 3, 'end', ha='center', va='center')
    # Adding grid lines to the plot
    ax.set_xticks(np.arange(-.5, 4, 1), minor=True)
    ax.set_yticks(np.arange(-.5, 4, 1), minor=True)
    ax.grid(which='minor', color='black', linestyle='-', linewidth=2)
    def update(t):
        sc.set_offsets(states[t])
    ani = FuncAnimation(fig,update,frames=len(states))
    display(IPython.display.HTML(ani.to_jshtml()))

In [5]:
show([[0,0]])

## Environment Class

In [6]:
action_space = gym.spaces.Discrete(4)
action_space.sample()

1

In [12]:
state_space = gym.spaces.MultiDiscrete([4,4])
state = state_space.sample()

In [17]:
action = 0
current_state = np.array([0,1])

In [18]:
action_to_direction = {
    0 : np.array([1,0]), # right
    1 : np.array([0,1]), # up
    2 : np.array([-1,0]), # left
    3 : np.array([0,-1]), # down
}

In [16]:
next_state = current_state + action_to_direction[action]
next_state

array([1, 0])

In [ ]:
# action = 0 <-> right // action = 1 <-> up

if action == 0:
    print(state + np.array([1,0]))
elif action == 1:  
    print(state + np.array([0,1]))

In [22]:
class GridWorld:
    def __init__(self):
        self.reset()
        self.state_space = gym.spaces.MultiDiscrete([4,4])
        self.action_space = gym.spaces.Discrete(4) 
        self._action_to_direction = { 
            0 : np.array([1, 0]), # x+ 
            1 : np.array([0, 1]), # y+ 
            2 : np.array([-1 ,0]), # x- 
            3 : np.array([0, -1]) # y- 
        }
    def reset(self):
        self.agent_action = None 
        self.agent_state = np.array([0,0])        
        return self.agent_state 
    def step(self,action):
        direction = self._action_to_direction[action]
        self.agent_state = self.agent_state + direction
        if self.agent_state not in env.state_space: # 4x4 그리드 밖에 있는 경우
            reward = -10 
            terminated = True
            self.agent_state = self.agent_state -1/2 * direction
        elif np.array_equal(env.agent_state, np.array([3,3])): # 목표지점에 도달할 경우 
            reward = 100 
            terminated = True
        else: 
            reward = -1 
            terminated = False         
        return self.agent_state, reward, terminated

In [23]:
env = GridWorld()

In [24]:
states = [env.agent_state]
for _ in range(5):
    states.append(env.step(0))

In [25]:
show(states)

[array([0, 0]),
 (array([1, 0]), -1, False),
 (array([2, 0]), -1, False),
 (array([3, 0]), -1, False),
 (array([3.5, 0. ]), -10, True),
 (array([4., 0.]), -10, True)]